# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Lg(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(330, 532)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Fcadastro = QtWidgets.QFrame(Dialog)
        self.Fcadastro.setMinimumSize(QtCore.QSize(312, 514))
        self.Fcadastro.setMaximumSize(QtCore.QSize(312, 514))
        self.Fcadastro.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Fcadastro.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Fcadastro.setObjectName("Fcadastro")
        self.label_4 = QtWidgets.QLabel(self.Fcadastro)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayoutWidget = QtWidgets.QWidget(self.Fcadastro)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 90, 281, 142))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.loginButton = QtWidgets.QPushButton(self.Fcadastro)
        self.loginButton.setGeometry(QtCore.QRect(110, 250, 75, 23))
        self.loginButton.setObjectName("loginButton")
        self.registerOpen = QtWidgets.QPushButton(self.Fcadastro)
        self.registerOpen.setGeometry(QtCore.QRect(230, 480, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.registerOpen.setFont(font)
        self.registerOpen.setFlat(True)
        self.registerOpen.setObjectName("registerOpen")
        self.horizontalLayout.addWidget(self.Fcadastro)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "Sign In"))
        self.label.setText(_translate("Dialog", "Username:"))
        self.label_3.setText(_translate("Dialog", "Password:"))
        self.loginButton.setText(_translate("Dialog", "Login"))
        self.registerOpen.setText(_translate("Dialog", "Sign Up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Lg()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
